packageExtensions:
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  mobx-react@*:
    peerDependencies:
      react-dom: "*"
  mongoose-id-validator@*:
    peerDependencies:
      mongoose: "*"
  tss-react@*:
    peerDependencies:
      "@mui/material": "*"
  "@jbrowse/core@*":
    peerDependencies:
      "@emotion/styled": "*"
      "@emotion/react": "*"
  material-ui-popup-state@*:
    peerDependencies:
      react-dom: "*"
      "@emotion/styled": "*"
      "@emotion/react": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
