enableConstraintsChecks: true

enableGlobalCache: false

packageExtensions:
  "@jbrowse/core@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  cypress-mongodb@*:
    dependencies:
      bson: ^4
  fancy-test@*:
    dependencies:
      chai: "*"
  material-ui-popup-state@*:
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      react-dom: "*"
  mobx-react@*:
    peerDependencies:
      react-dom: "*"
  mocha@*:
    dependencies:
      source-map-support: "*"
      ts-node: "*"
  mongoose-id-validator@*:
    peerDependencies:
      mongoose: "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
