approvedGitRepositories:
  - "**"

enableConstraintsChecks: true

enableGlobalCache: false

enableScripts: true

npmMinimalAgeGate: 2880

npmPreapprovedPackages:
  - "@gmod/*"
  - "@jbrowse/*"

packageExtensions:
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependenciesMeta:
      search-insights:
        optional: true
  "@algolia/autocomplete-shared@*":
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
      algoliasearch:
        optional: true
  "@cypress/code-coverage@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      "@babel/preset-env":
        optional: true
      babel-loader:
        optional: true
      webpack:
        optional: true
  "@cypress/webpack-preprocessor@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      "@babel/preset-env":
        optional: true
      babel-loader:
        optional: true
      webpack:
        optional: true
  "@docusaurus/babel@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/bundler@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils-common@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils-validation@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-css-cascade-layers@*":
    peerDependencies:
      "@mdx-js/react": "*"
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-debug@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-analytics@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-gtag@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-tag-manager@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-svgr@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@jbrowse/core@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@jbrowse/plugin-linear-genome-view@*":
    peerDependencies:
      "@emotion/styled": "*"
  "@jbrowse/product-core@*":
    peerDependencies:
      "@emotion/styled": "*"
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  cypress-mongodb@*:
    dependencies:
      bson: ^4
  eslint-plugin-import-x@*:
    peerDependencies:
      "@typescript-eslint/parser": "*"
  eslint-plugin-tsdoc@*:
    peerDependencies:
      eslint: "*"
      typescript: "*"
  material-ui-popup-state@*:
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      react-dom: "*"
  mobx-react@*:
    peerDependencies:
      react-dom: "*"
  mongoose-id-validator@*:
    peerDependencies:
      mongoose: "*"
  rollup-plugin-external-globals@*:
    peerDependenciesMeta:
      rollup:
        optional: true
  vue-router@*:
    peerDependenciesMeta:
      vue:
        optional: true

yarnPath: .yarn/releases/yarn-4.18.0.cjs
