packageExtensions:
  "@jbrowse/core@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  cypress-mongodb@*:
    dependencies:
      bson: ^4
  material-ui-popup-state@*:
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      react-dom: "*"
  mobx-react@*:
    peerDependencies:
      react-dom: "*"
  mongoose-id-validator@*:
    peerDependencies:
      mongoose: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
