name: apollo

services:
  apollo-collaboration-server:
    build:
      dockerfile: ./server.Dockerfile
    volumes:
      - uploaded-files-volume:/data/uploads
    env_file: ./docker/.development.env
    secrets:
      - mongodb-uri
      - google-client-id
      - google-client-secret
      - microsoft-client-id
      - microsoft-client-secret
      - jwt-secret
      - session-secret
    depends_on:
      mongodb-init:
        condition: service_completed_successfully

  client:
    build:
      dockerfile: ./client.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/config:/usr/local/apache2/htdocs/data

  mongodb:
    image: mongo
    volumes:
      - mongodb-volume:/data/db
    command: --replSet rs0

  # this container will exit after initializing the replica set
  mongodb-init:
    image: mongo
    depends_on:
      - mongodb
    command: sleep 5 && mongosh mongodb://mongodb:27017 --eval 'try {rs.initiate();} catch {}'

volumes:
  mongodb-volume: null
  uploaded-files-volume: null

secrets:
  mongodb-uri:
    file: ./docker/mongodb-uri
  google-client-id:
    file: ./docker/google-client-id
  google-client-secret:
    file: ./docker/google-client-secret
  microsoft-client-id:
    file: ./docker/microsoft-client-id
  microsoft-client-secret:
    file: ./docker/microsoft-client-secret
  jwt-secret:
    file: ./docker/jwt-secret
  session-secret:
    file: ./docker/session-secret
