services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    command: --replSet rs0 --setParameter "transactionLifetimeLimitSeconds=300"
    healthcheck:
      test:
        mongosh --eval 'try
        {rs.initiate({_id:"rs0",members:[{_id:0,host:"localhost:27017"}]});}
        catch(e) {}' --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb-data:
