services:
  apollo-collaboration-server:
    image: ghcr.io/gmod/apollo-collaboration-server:${DOCKER_TAG}
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      NAME: Apollo demo server
      MONGODB_URI: mongodb://mongo:27017/apolloDb
      FILE_UPLOAD_FOLDER: /data/uploads
      LOG_LEVELS: error,warn,log,debug
      NO_COLOR: true
      ALLOW_GUEST_USER: true
      DEFAULT_NEW_USER_ROLE: user
      URL: ${URL}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      ALLOW_ROOT_USER: true
      ROOT_USER_PASSWORD: ${ROOT_USER_PASSWORD}
    volumes:
      - uploaded-files-volume:/data/uploads
    restart: unless-stopped

  client:
    build:
      context: .
    depends_on:
      - apollo-collaboration-server
    ports:
      - ${PORT}:80
    volumes:
      - /home/ec2-user/deployment/data-${ENVIRONMENT}/:/usr/local/apache2/htdocs/data/
    restart: unless-stopped

  mongo:
    image: mongo:7
    healthcheck:
      interval: 30s
      retries: 3
      start_interval: 5s
      start_period: 2m
      test: |
        mongosh --quiet --eval "db.runCommand('ping')"
      timeout: 10s
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: unless-stopped

volumes:
  mongo_config: null
  mongo_data: null
  uploaded-files-volume: null
