version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:16.1.1
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
      KEYCLOAK_IMPORT: /tmp/keycloak-realm.json
    volumes:
      - ./.docker/keycloak-realm.json:/tmp/keycloak-realm.json
