default:
  address: http://localhost:3999
  accessType: root
  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhcmlvIEJlcmFsZGkiLCJlbWFpbCI6ImRhcmlvLmJlcmFsZGlAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWQiOiI2NWNjYzE4OGQ5MmM2MjRjMzEyODA0MmYiLCJpYXQiOjE3MDg2MDExODAsImV4cCI6MTcwODY4NzU4MH0.MUeMiiHO3kd4q7_1gVeQbYALUjOhN4DxGhibeIWzy_g
  rootCredentials:
    username: root
    password: '1234'
profile1:
  address: http://localhost:1999
  accessToken: xyz
noAccessToken:
  address: http://localhost:1999
test1:
  address: http://localhost:3999
  accessType: google
