name: Build and upload artifacts

on:
  workflow_call:

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Install
        run: yarn --immutable
      - name: Build collaboration server
        run: yarn build
        working-directory: packages/apollo-collaboration-server
      - name: Build plugin
        run: yarn build
        working-directory: packages/jbrowse-plugin-apollo
      - name: Upload built plugin files
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: |
            packages/jbrowse-plugin-apollo/dist/jbrowse-plugin-apollo.umd.development.js
            packages/jbrowse-plugin-apollo/dist/jbrowse-plugin-apollo.umd.production.min.js
