name: Build and push docker

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - latest

jobs:
  build-and-push-docker:
    name: Build and push Docker image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Apollo CLI image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/gmod/apollo-cli:${{ inputs.tag }}
          file:
            ${{ inputs.tag == 'dev' && 'packages/apollo-cli/dev.Dockerfile' ||
            'packages/apollo-cli/Dockerfile' }}
          outputs:
            type=image,annotation-index.org.opencontainers.image.description=
            Apollo CLI
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
      - name: Build and push Apollo collaboration server image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/gmod/apollo-collaboration-server:${{ inputs.tag }}
          outputs:
            type=image,annotation-index.org.opencontainers.image.description=Apollo
            collaboration server
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
