name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: |
          npm publish package/apollo-common 
          npm publish package/apollo-mst 
          npm publish package/apollo-schemas 
          npm publish package/apollo-shared
          npm publish package/jbrowse-plugin-apollo
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
