name: Weekly cleanup of data on demo servers

on:
  schedule:
    - cron: 13 9 * * MON

jobs:
  prod-cleanup:
    name: Clean up prod demo server
    runs-on: ubuntu-latest
    uses: ./.github/workflows/reload_demo_data.yml
    with:
      environment: prod
  staging-cleanup:
    name: Clean up staging demo server
    runs-on: ubuntu-latest
    uses: ./.github/workflows/reload_demo_data.yml
    with:
      environment: staging
